In [2]:
import pandas as pd
import numpy as np
import string
import nltk
import joblib
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
nltk.download('stopwords')
nltk.download('punkt_tab')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Amit\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Amit\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [3]:
df = pd.read_csv('spam.csv', encoding='latin-1')
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [4]:
df = df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1)

In [5]:
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
df.isnull().sum()

v1    0
v2    0
dtype: int64

In [7]:
df.shape

(5572, 2)

In [8]:
df['v1'].unique()

array(['ham', 'spam'], dtype=object)

In [9]:
df_copy = df.copy()

In [10]:
pd.set_option('display.max_colwidth', None) 
pd.set_option('display.width', 1000)

In [11]:
df_copy['cleaned_column'] = df_copy['v2'].str.lower()

In [12]:
df_copy.head(10)

     v1                                                                                                                                                                v2                                                                                                                                                    cleaned_column
0   ham                                                   Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...                                                   go until jurong point, crazy.. available only in bugis n great world la e buffet... cine there got amore wat...
1   ham                                                                                                                                     Ok lar... Joking wif u oni...                                                                                                                                     ok lar... joking wif u oni...
2  spam       Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's       free entry in 2 a wkly comp to win fa cup final tkts 21st may 2005. text fa to 87121 to receive entry question(std txt rate)t&c's apply 08452810075over18's
3   ham                                                                                                                 U dun say so early hor... U c already then say...                                                                                                                 u dun say so early hor... u c already then say...
4   ham                                                                                                     Nah I don't think he goes to usf, he lives around here though                                                                                                     nah i don't think he goes to usf, he lives around here though
5  spam              FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, å£1.50 to rcv              freemsg hey there darling it's been 3 week's now and no word back! i'd like some fun you up for it still? tb ok! xxx std chgs to send, å£1.50 to rcv
6   ham                                                                                     Even my brother is not like to speak with me. They treat me like aids patent.                                                                                     even my brother is not like to speak with me. they treat me like aids patent.
7   ham  As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune  as per your request 'melle melle (oru minnaminunginte nurungu vettam)' has been set as your callertune for all callers. press *9 to copy your friends callertune
8  spam    WINNER!! As a valued network customer you have been selected to receivea å£900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.    winner!! as a valued network customer you have been selected to receivea å£900 prize reward! to claim call 09061701461. claim code kl341. valid 12 hours only.
9  spam        Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030        had your mobile 11 months or more? u r entitled to update to the latest colour mobiles with camera for free! call the mobile update co free on 08002986030

In [13]:
df_copy['cleaned_column'] = df_copy['cleaned_column'].replace('[' + string.punctuation + ']', '', regex=True)

In [14]:
df_copy.head(10)

     v1                                                                                                                                                                v2                                                                                                                                              cleaned_column
0   ham                                                   Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...                                                      go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat
1   ham                                                                                                                                     Ok lar... Joking wif u oni...                                                                                                                                     ok lar joking wif u oni
2  spam       Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's       free entry in 2 a wkly comp to win fa cup final tkts 21st may 2005 text fa to 87121 to receive entry questionstd txt ratetcs apply 08452810075over18s
3   ham                                                                                                                 U dun say so early hor... U c already then say...                                                                                                                 u dun say so early hor u c already then say
4   ham                                                                                                     Nah I don't think he goes to usf, he lives around here though                                                                                                 nah i dont think he goes to usf he lives around here though
5  spam              FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, å£1.50 to rcv                freemsg hey there darling its been 3 weeks now and no word back id like some fun you up for it still tb ok xxx std chgs to send å£150 to rcv
6   ham                                                                                     Even my brother is not like to speak with me. They treat me like aids patent.                                                                                 even my brother is not like to speak with me they treat me like aids patent
7   ham  As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune  as per your request melle melle oru minnaminunginte nurungu vettam has been set as your callertune for all callers press 9 to copy your friends callertune
8  spam    WINNER!! As a valued network customer you have been selected to receivea å£900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.    winner as a valued network customer you have been selected to receivea å£900 prize reward to claim call 09061701461 claim code kl341 valid 12 hours only
9  spam        Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030    had your mobile 11 months or more u r entitled to update to the latest colour mobiles with camera for free call the mobile update co free on 08002986030

In [15]:
stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    tokens = word_tokenize(text)
    filtered_tokens = [w for w in tokens if w.lower() not in stop_words]
    return ' '.join(filtered_tokens)

df_copy['cleaned_column'] = df_copy['cleaned_column'].apply(remove_stopwords)

In [16]:
df_copy.head(10)

     v1                                                                                                                                                                v2                                                                                                                           cleaned_column
0   ham                                                   Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...                                                       go jurong point crazy available bugis n great world la e buffet cine got amore wat
1   ham                                                                                                                                     Ok lar... Joking wif u oni...                                                                                                                  ok lar joking wif u oni
2  spam       Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's  free entry 2 wkly comp win fa cup final tkts 21st may 2005 text fa 87121 receive entry questionstd txt ratetcs apply 08452810075over18s
3   ham                                                                                                                 U dun say so early hor... U c already then say...                                                                                                      u dun say early hor u c already say
4   ham                                                                                                     Nah I don't think he goes to usf, he lives around here though                                                                                              nah dont think goes usf lives around though
5  spam              FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, å£1.50 to rcv                                                freemsg hey darling 3 weeks word back id like fun still tb ok xxx std chgs send å£150 rcv
6   ham                                                                                     Even my brother is not like to speak with me. They treat me like aids patent.                                                                                           even brother like speak treat like aids patent
7   ham  As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune                        per request melle melle oru minnaminunginte nurungu vettam set callertune callers press 9 copy friends callertune
8  spam    WINNER!! As a valued network customer you have been selected to receivea å£900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.               winner valued network customer selected receivea å£900 prize reward claim call 09061701461 claim code kl341 valid 12 hours
9  spam        Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030                            mobile 11 months u r entitled update latest colour mobiles camera free call mobile update co free 08002986030

In [17]:
df_copy['cleaned_column'] = df_copy['cleaned_column'].str.strip()

In [18]:
df_copy.head(10)

     v1                                                                                                                                                                v2                                                                                                                           cleaned_column
0   ham                                                   Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...                                                       go jurong point crazy available bugis n great world la e buffet cine got amore wat
1   ham                                                                                                                                     Ok lar... Joking wif u oni...                                                                                                                  ok lar joking wif u oni
2  spam       Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's  free entry 2 wkly comp win fa cup final tkts 21st may 2005 text fa 87121 receive entry questionstd txt ratetcs apply 08452810075over18s
3   ham                                                                                                                 U dun say so early hor... U c already then say...                                                                                                      u dun say early hor u c already say
4   ham                                                                                                     Nah I don't think he goes to usf, he lives around here though                                                                                              nah dont think goes usf lives around though
5  spam              FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, å£1.50 to rcv                                                freemsg hey darling 3 weeks word back id like fun still tb ok xxx std chgs send å£150 rcv
6   ham                                                                                     Even my brother is not like to speak with me. They treat me like aids patent.                                                                                           even brother like speak treat like aids patent
7   ham  As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune                        per request melle melle oru minnaminunginte nurungu vettam set callertune callers press 9 copy friends callertune
8  spam    WINNER!! As a valued network customer you have been selected to receivea å£900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.               winner valued network customer selected receivea å£900 prize reward claim call 09061701461 claim code kl341 valid 12 hours
9  spam        Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030                            mobile 11 months u r entitled update latest colour mobiles camera free call mobile update co free 08002986030

In [19]:
df_copy['v1'] = df_copy['v1'].map({"ham":0, "spam":1})

In [20]:
X = df_copy['cleaned_column']
y = df_copy['v1']

X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.25, random_state = 42)

In [21]:
tf = TfidfVectorizer()

In [22]:
X_train_tfidf = tf.fit_transform(X_train)

In [23]:
X_test_tfidf = tf.transform(X_test)

In [25]:
print(X_train_tfidf.shape)
print(X_test_tfidf.shape)

(4179, 7946)
(1393, 7946)

In [26]:
model = LogisticRegression()

In [27]:
model.fit(X_train_tfidf, y_train)

LogisticRegression()

In [28]:
y_pred = model.predict(X_test_tfidf)

In [29]:
accuracy_score(y_test, y_pred)

0.9490308686288585

In [30]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97      1202
           1       0.96      0.65      0.78       191

    accuracy                           0.95      1393
   macro avg       0.95      0.83      0.88      1393
weighted avg       0.95      0.95      0.94      1393

In [31]:
joblib.dump(model, 'spam_model.pkl')

['spam_model.pkl']

In [32]:
joblib.dump(tf, 'tfidf_Vectorizer.pkl')

['tfidf_Vectorizer.pkl']

In [41]:
def remove_punctuation(text):
    translator = str.maketrans('','', string.punctuation)
    return text.translate(translator)

test = "Congratulations! You have won a FREE prize. Claim your reward now."
test = test.lower()
test = remove_stopwords(test)
test = remove_punctuation(test)
test = test.strip()
print(test)

congratulations  free prize  claim reward

In [44]:
model.predict(
    tf.transform([test])
)

model.predict_proba(
    tf.transform([test])
)

array([[0.11602942, 0.88397058]])